---

compile_flags:
 - -Wall
 - -Werror
 - -Winvalid-pch
 - -std=c++17
   # - -H

debug_compile_flags:
 - -g

link_flags:
 - -Wall
 
debug_link_flags:
 - -export-dynamic
 - -Xlinker

include_dirs:
 - include/
 - include/event
 - extern/spdlog/include

libs:
 - dl
 - glfw
 - GL

lib_paths:
