---

compile_flags:
 - '/EHsc'
 - '/MD'

debug_compile_flags:
 - '/DEBUG'
 - '/Z7'

link_flags:
 
debug_link_flags:
 - '/DEBUG'

include_dirs:
 - include/

libs:

lib_paths:
 - $(WIN_KIT_DIR)/Windows Kits/10/Lib/10.0.14393.0/um/x86/
