---

compile_flags:
 - -Wall

debug_compile_flags:
 - -g

link_flags:
 - -Wall
 
debug_link_flags:
 - -export-dynamic
 - -Xlinker

include_dirs:
 - include/
 - extern/imgui/
 - /usr/include/python3.6/
 - /usr/include/GL/
 - /usr/local/include/GLFW/
 - /home/campbell/Projects/Libraries/soil/src/
 - /home/campbell/Projects/Libraries/glm-0.9.9.0/
 - /home/campbell/Projects/Libraries/shapelib-1.4.0/
 - /home/campbell/Projects/WorldEngine/include/

libs:
 - python3.6m
 - pthread
 - dl
 - util
 - m
 - GL
 - GLU
 - GLEW
 - Xi
 - Xmu
 - glfw
 - SOIL
 - shp
 - assimp

lib_paths:
 - /usr/lib
 - /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu
