# Objects
---
- #!object
  name: Cube instance 1
  transform: #!transform
    translation: #!vec3
      x: 1.0
      y: 2.0
      z: 3.0
    rotation:
    scale: #!vec3
      x: 0.5
      y: 0.5
      z: 0.5
  mesh:
    name: Cube
  light:
  script: cube
