---

compile_flags:
 - '/EHsc'
 - '/MD'

debug_compile_flags:
 - '/DEBUG'
 - '/Z7'

link_flags:
 - '/NODEFAULTLIB:libcmt.lib'
 - '/LTCG' 
 
debug_link_flags:
 - '/DEBUG'

include_dirs:
 - include/
 - extern/imgui/
 - $(EXTERNAL_LIBS)
 - $(EXTERNAL_LIBS)/assimp-4.0.1/include
 - $(EXTERNAL_LIBS)/freetype/include/freetype2
 - $(EXTERNAL_LIBS)/glew-2.0.0/include
 - $(EXTERNAL_LIBS)/glfw-3.2.1.bin.WIN32/include
 - $(EXTERNAL_LIBS)/glm
 - $(PYTHON_PATH)/include
 - $(EXTERNAL_LIBS)/shapelib-1.4.0
 - $(EXTERNAL_LIBS)/soil/include

libs:
 - python36.lib
 - python36_d.lib
 - User32.lib
 - Gdi32.lib
 - OpenGL32.lib
 - kernel32.lib
 - shell32.lib
 - glfw3.lib
 - glew32s.lib
 - SOIL.lib
 - freetype.lib
 - assimp.lib
 - IrrXML.lib
 - zlibstatic.lib
 - shapelib.lib

lib_paths:
 - $(PYTHON_PATH)libs/
 - $(WIN_KIT_DIR)/Windows Kits/10/Lib/10.0.14393.0/um/x86/
 - $(EXTERNAL_LIBS)/glfw-3.2.1.bin.WIN32/lib-vc2015/
 - $(EXTERNAL_LIBS)/glew-2.0.0/lib/Release/Win32/
 - $(EXTERNAL_LIBS)/soil/lib/
 - $(EXTERNAL_LIBS)/freetype/lib/
 - $(EXTERNAL_LIBS)/assimp-4.0.1/lib/
 - $(EXTERNAL_LIBS)/shapelib-1.4.0/
